2025-03-12 16:53:23,422 - clemcore.cli - INFO - Found '1' game matching the game_selector="desktopgame"
2025-03-12 16:53:23,423 - clemcore.cli - INFO - {
  "game_name": "desktopgame",
  "game_path": "/Users/nidhirbhavsar/Desktop/WORK/thesis/clembench_nidhir",
  "description": "A game where an agent interacts with a desktop environment",
  "main_game": "desktopgame",
  "players": "one",
  "image": "none",
  "languages": [
    "en"
  ],
  "benchmark": []
}
2025-03-12 16:53:23,424 - clemcore.cli - INFO - Found registered model spec that unifies with {"model_name":"gpt-4o-2024-08-06"} -> {'model_name': 'gpt-4o-2024-08-06', 'backend': 'openai', 'estimated_parameters': '200B', 'lookup_source': '/Users/nidhirbhavsar/Desktop/WORK/thesis/clembench_nidhir/model_registry.json', 'model_id': 'gpt-4o-2024-08-06', 'open_weight': False, 'parameters': '', 'release_date': '2024-08-06', 'support_multiple_images': True, 'supports_images': True}
2025-03-12 16:53:23,424 - clemcore.cli - INFO - Found registry entry for backend openai -> {'backend': 'openai', 'file_name': 'openai_api.py', 'file_path': '/Users/nidhirbhavsar/Desktop/WORK/thesis/clemcore/clemcore/backends/openai_api.py', 'lookup_source': 'packaged'}
2025-03-12 16:53:23,424 - clemcore.cli - INFO - Dynamically import backend openai
2025-03-12 16:53:23,842 - clemcore.cli - INFO - Successfully loaded gpt-4o-2024-08-06 model
2025-03-12 16:53:23,842 - clemcore.run - INFO - Loading game benchmark for desktopgame
2025-03-12 16:53:23,843 - clemcore.cli - ERROR - [Errno 2] No such file or directory: '/Users/nidhirbhavsar/Desktop/WORK/thesis/clembench_nidhir/master.py'
Traceback (most recent call last):
  File "/Users/nidhirbhavsar/Desktop/WORK/thesis/clemcore/clemcore/cli.py", line 121, in run
    with benchmark.load_from_spec(game_spec, instances_name=instances_name) as game_benchmark:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.7/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/Desktop/WORK/thesis/clemcore/clemcore/clemgame/benchmark.py", line 353, in load_from_spec
    spec.loader.exec_module(game_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nidhirbhavsar/Desktop/WORK/thesis/clembench_nidhir/master.py'
2025-03-12 16:53:23,844 - clemcore.cli - ERROR - [Errno 2] No such file or directory: '/Users/nidhirbhavsar/Desktop/WORK/thesis/clembench_nidhir/master.py'
Traceback (most recent call last):
  File "/Users/nidhirbhavsar/Desktop/WORK/thesis/clemcore/clemcore/cli.py", line 121, in run
    with benchmark.load_from_spec(game_spec, instances_name=instances_name) as game_benchmark:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.7/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/Desktop/WORK/thesis/clemcore/clemcore/clemgame/benchmark.py", line 353, in load_from_spec
    spec.loader.exec_module(game_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nidhirbhavsar/Desktop/WORK/thesis/clembench_nidhir/master.py'
